### ISSUE TITLE
Описание логики работы программы

### ISSUE THREAD

**Issue by medvoodoo** [YuriyCherniy/lzy.su#1]
Мы переписывались на пикабу, возникли еще несколько вопросов:
1. Какой алгоритм сокращателя ссылок ( если честно лень полностью разбираться), есть ли тз
2. Как сервис работает с русскоязычными доменами, типа https://стопкоронавирус.рф импортирует ли он эти ссылки?

**Comment by YuriyCherniy** [comment]
1. Короткая ссылка генерируется из  id записи в базе данных. Алгоритм не самописный, я воспользовался вот этим проектом [hashids.org](https://hashids.org) Вот его  Python  реализация [github.com/davidaurelio/hashids-python](https://github.com/davidaurelio/hashids-python)
2. Вопрос немного не понял, но все работает так же как и с англоязычными доменами.

**Comment by medvoodoo** [comment]
я тогда не очень понимаю, зачем его было копировать, если его можно через pip поставить и подключить? Второе, я не очень уверен, что это подходящий алгоритм, они пишут, что не хотят кешировать строки, а у вас будут складываться get запросы и какие нить реакт, которые могут содержать # и кто знает, что еще.

**Comment by YuriyCherniy** [comment]
1. Если ставить через pip появляется проблема с импортом модуля. Проблема известная, глубоко не копал, просто положил модуль в проект.
2. Они не то, что не хотят, они прямо говорят:

> Do not encode strings

Проекту это и не надо, кодируются только числа.
